/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DataCleaningPhase.java
 *
 
 */
package com.ui;

import com.auth.DataOperations;
import com.logic.GlobalClass;
import com.logic.LoadData;
import java.io.FileOutputStream;
import java.io.PrintWriter;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author Administrator
 */
public class DataCleaningPhase extends javax.swing.JFrame {

    String header;
    Object []headers;
    Object [][]data;
    static Object [][]cdata;
    int rowno=-1;
    /** Creates new form DataCleaningPhase */
    public DataCleaningPhase() {
        initComponents();
        loadData();
        bindData();
    }
    
    private void bindData()
    {
       TableModel tm=new DefaultTableModel(data, headers);
       tblOriginal.setModel(tm);
    }
    
    private void loadData() 
    {
        try
        {
         DataOperations dp=new DataOperations();
         ResultSet rs=dp.getData();
         ResultSetMetaData rsmd=rs.getMetaData();

         headers=new Object[rsmd.getColumnCount()];
         for(int i=1;i<=rsmd.getColumnCount();i++)
             headers[i-1]=rsmd.getColumnName(i);
         
         data=new Object[dp.getRowCount()][headers.length];
         rowno=0;
         while(rs.next())
         {
               for(int i=1;i<=rsmd.getColumnCount();i++)
                    data[rowno][i-1]=rs.getString(i);
               rowno++;
         }
         rs.close();
        }
         catch(Exception ex)
         {
             System.out.println("Error Occurred In Data Loading Process ");
         }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOriginal = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblClean = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setName("jTable2"); // NOI18N
        jScrollPane2.setViewportView(jTable2);

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.setName("jTable3"); // NOI18N
        jScrollPane3.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(churnpredictor_telecom.ChurnPredictor_TelecomApp.class).getContext().getResourceMap(DataCleaningPhase.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setBounds(new java.awt.Rectangle(200, 100, 400, 400));
        setName("Form"); // NOI18N
        setResizable(false);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblOriginal.setFont(resourceMap.getFont("tblOriginal.font")); // NOI18N
        tblOriginal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblOriginal.setName("tblOriginal"); // NOI18N
        jScrollPane1.setViewportView(tblOriginal);

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        tblClean.setFont(resourceMap.getFont("tblClean.font")); // NOI18N
        tblClean.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblClean.setName("tblClean"); // NOI18N
        jScrollPane4.setViewportView(tblClean);

        jButton1.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(resourceMap.getColor("jPanel2.background")); // NOI18N
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setName("jPanel2"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(284, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(258, 258, 258))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, 0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       MainMenu mf=new MainMenu();
        this.setVisible(false);
        mf.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cdata=new Object[data.length][headers.length];
        rowno=0;
        boolean flag=true;
        try
        {
            for(int i=0;i<data.length;i++)
            {
                for(int j=0;j<headers.length;j++)
                {
                     if(data[i][j].toString().equals("?") || data[i][j].toString().trim().equals(""))
                     {
                         flag=false;
                          break;
                          }
                }
                if(flag)
                {
                      cdata[rowno]=data[i];
                      rowno++;
                }
            flag=true;                
            }
            
            TableModel tm=new DefaultTableModel(cdata, headers);
            tblClean.setModel(tm);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,"Error In Data Cleaning Process");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void createNewFile(String header,String data)
    {
        try
        {
            FileOutputStream fos=new FileOutputStream("input//cleaninput.txt");
            PrintWriter pw=new PrintWriter(fos);
            String headerpart="";
            String []colheaders=header.split(",");
            System.out.println(colheaders.length);
            for(int i=0;i<colheaders.length;i++)
                headerpart+=colheaders[i] + ",";
            headerpart=headerpart.substring(0,headerpart.length()-1);
            System.out.println(header + "\n" + headerpart);
            pw.println(headerpart);
            
            
            StringTokenizer st=new StringTokenizer(data,"\r\n");
            String insertstmt="";
        while(st.hasMoreElements())
            {
            String row=st.nextElement().toString();
            String elements[]=row.split(",");
            
            for(int i=0;i<elements.length;i++)
                insertstmt+=elements[i]+",";
            insertstmt=insertstmt.substring(0,insertstmt.length()-1);
            pw.println(insertstmt);
            insertstmt="";
            }
        pw.close();
        fos.close();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,"Error inSaving ");
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        StringBuilder sb=new StringBuilder();
        for(int i=0;i<rowno;i++)
        {
                for(int j=0;j<headers.length;j++)
                    if(j==headers.length)
                        sb.append(cdata[i][j]);
                else
                     sb.append(cdata[i][j]+",");
                sb.append("\r\n");
        }
       DataOperations create=new DataOperations();
       if(create.createCDyanamicTable(LoadData.colnames))
         {
           if(create.insertCData(sb.toString()))
           {
               JOptionPane.showMessageDialog(this, "Data Cleaned Successfully...");
               LoadData.stage="1";
               GlobalClass.stage=2;
               createNewFile(LoadData.getHeader(),sb.toString());
           }
            else
          JOptionPane.showMessageDialog(this, "Error while data Cleaning");
        }
 else
      JOptionPane.showMessageDialog(this, "Error while creating object");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DataCleaningPhase().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable tblClean;
    private javax.swing.JTable tblOriginal;
    // End of variables declaration//GEN-END:variables
}
